Add support for docker compose in l0-auth repo
tiki/l0-auth pull request #14
Opened 2022-11-21 22:51 UTC by wsb1994

Draft in progress

2022-11-22 17:55 UTC, wsb1994 commented
Ignore everything that isn't infra related, rebasing was hell so I just copy pasted the main updated branch into the new repo setup. If you download and look at the code that's probably the best way to handle this particular review since it fully restructures the entire repo.

2022-11-28 22:56 UTC, wsb1994 commented
@timoguin

2022-11-30 03:52 UTC, mike-audi commented
@wsb1994 

I got this working (mostly)

It still needs the following fixes before we can merge it into dev

- need to figure out how to run the create table script in database/
- need to test prod deployment to make sure we didn't break anything in the CI/CD
- need to setup debugging & junit test exec (https://www.jetbrains.com/help/idea/run-and-debug-a-spring-boot-application-using-docker-compose.html#launch_debug_config)
- need to add a doc on how to use it

2022-11-30 03:53 UTC, wsb1994 commented
Looking at this first thing tomorrow 🤜🤛

On Tue, Nov 29, 2022 at 9:52 PM Mike Audi ***@***.***> wrote:

> @wsb1994 <https://github.com/wsb1994>
>
> I got this working (mostly)
>
> It still needs the following fixes before we can merge it into dev
>
>    - need to figure out how to run the create table script in database/
>    - need to test prod deployment to make sure we didn't break anything
>    in the CI/CD
>    - need to setup debugging & junit test exec (
>    https://www.jetbrains.com/help/idea/run-and-debug-a-spring-boot-application-using-docker-compose.html#launch_debug_config
>    )
>    - need to add a doc on how to use it
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tiki/l0-auth/pull/14#issuecomment-1331610400>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIWJSDYB4OHWHDQNVH4CYPLWK3FPPANCNFSM6AAAAAASHEPY34>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-12-01 19:35 UTC, wsb1994 commented
Excellent progress homies gonna try and take a look at a migration system that isn't *wonky* so we can help contributors get set up easily. I had an off-github conversation about this and have some avenues to approach doing this. 

Will update with that effort soon.

2022-12-19 16:03 UTC, wsb1994 commented
Automigration is functional @mike-audi @timoguin

2022-12-19 16:08 UTC, wsb1994 commented on docker-compose.yaml
> +      - 5432:5432
note: I noticed I have altered the default port I launch PG on. if this is an issue I can fix it.

2022-12-19 18:18 UTC, timoguin commented on docker-compose.yaml
> +      - 5432:5432
That's the default port for Postgres anyway, so that's fine.

2022-12-19 18:25 UTC, timoguin commented on database/create_tables.sql
> +    jti UUID NOT NULL,
We should leave the `database/` folder because it's much more clear than `docker-entrypoint-initdb.d/`.

Instead of changing the directory, we can just mount `database/` into the expected location inside the Postgres container, and then it will run the SQL files all the same.

2022-12-19 18:30 UTC, timoguin requested changes
I added a few notes. I'll help you get this rebased so we're not seeing such a large diff. Too many changes for my comfort level.

2022-12-19 18:30 UTC, timoguin commented on docker-compose.yaml
> +      - spring-postgres
We can leave out the network settings altogether, and then a default network will be created. So you don't have to define the top-level `networks` key, and you don't have to define it at the service level either.

2022-12-19 18:30 UTC, timoguin commented on docker-compose.yaml
> +      # - "./cloudquery-data/postgres:/var/lib/postgresql/data"
Drop this guy.

2022-12-19 18:40 UTC, wsb1994 commented on docker-compose.yaml
> +      - spring-postgres
sure thing!

2022-12-19 18:41 UTC, wsb1994 commented on docker-compose.yaml
> +      # - "./cloudquery-data/postgres:/var/lib/postgresql/data"
think I know what you mean but I'll leave it open for clarification

2022-12-19 18:42 UTC, wsb1994 commented on database/create_tables.sql
> +    jti UUID NOT NULL,
sure thing. I'll look into how to do this or follow up on this -> whichever is more appropriate

2022-12-19 23:40 UTC, wsb1994 commented on database/create_tables.sql
> +    jti UUID NOT NULL,
Done!

2022-12-20 00:19 UTC, merged

2022-12-20 03:25 UTC, timoguin approved these changes